@startuml view
title 6. Диаграмма кооперации (Просмотр фильма)
' Объявляем участников

actor "Пользователь" as U
node "Приложение" as App
node "Сервер" as S
database "БД" as DB
' Сначала пользователь выбирает контент
U -> App : 1.выбор фильма
' Приложение передает запрос на бэкенд
App -> S : 2.запустить фильм
' Сервер проверяет наличие фильма в базе данных
S -> DB : 3.поиск фильма
' База возвращает данные серверу
DB --> S : 4.Результат поиска
' Сервер отдает ссылку приложению для запуска плеера
S --> App : 5.Передача ссылки на видео
@enduml